### ISSUE TITLE
TypeError is thrown during integration test run.

### ISSUE THREAD

**Issue by seanttaylor** [seanttaylor/whosez-app#8]
A `TypeError` is thrown (stack trace below) during integration test runs launched from the command line via newman with `$npm run test:integration`. All test cases pass but we want to squash this bug so test runs aren't producing any additional noise.

The expected behavior is that the all tests pass with no random errors during the test run.

I suspect it has to do with the fact that the test run performs all the API calls in rapid succession. Since the polls are closed after a `setTimeout`, it's possible a subtle race condition is occurring. When the API calls that comprise the test run are run individually and in sequence from the Postman app, no error is thrown. 

```
TypeError: Cannot read property 'map' of null
    at EventEmitter.onPollFinalized (/app/src/karma-ledger/index.js:21:42)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at db.collection.update.then.then (/app/src/api/polls/index.js:26:29)
    at <anonymous>
```

**Comment by seanttaylor** [comment]
This issue was being caused by polls that result in `NO-CONENSUS`. The `minority` and `majority`  property on poll objects is `null` in the case of tie votes. Thus the `TypeError` thrown on the map method called on `null`.
